export const userIconTokens = {
  wrapper: 'relative',
  triggerBtn: 'w-8 h-8 rounded-full bg-primary-btn flex items-center justify-center overflow-hidden flex-shrink-0',
  initials: 'font-secondary font-black text-xs text-bg-dark',
  dropdown: 'absolute right-0 top-full mt-2 w-64 bg-bg-white dark:bg-bg-surface rounded-card-lg shadow-newsletter border border-border-primary/10 dark:border-white/10 overflow-hidden z-50',
  dropdownHeader: 'px-4 py-4 bg-bg-page dark:bg-bg-dark border-b border-border-primary/10 dark:border-white/10',
  dropdownHeaderInner: 'flex items-center gap-3',
  avatar: 'w-11 h-11 rounded-full bg-primary-btn flex items-center justify-center overflow-hidden flex-shrink-0',
  avatarInitials: 'font-secondary font-black text-sm text-bg-dark',
  userInfo: 'min-w-0',
  userName: 'text-sm font-semibold text-text-primary dark:text-text-on-dark truncate',
  userEmail: 'text-xs text-text-secondary dark:text-text-footer-link truncate',
  menuNav: 'py-1',
  menuItem: 'flex items-center gap-3 px-4 py-2.5 text-sm text-text-primary dark:text-text-on-dark hover:bg-bg-page dark:hover:bg-bg-dark transition-colors group',
  menuItemIcon: 'w-4 h-4 text-text-secondary dark:text-text-footer-link group-hover:text-primary-btn transition-colors flex-shrink-0',
  menuItemLabel: 'flex-1',
  menuItemChevron: 'w-3 h-3 text-text-secondary opacity-0 group-hover:opacity-100 transition-opacity',
  signOutSection: 'border-t border-border-primary/10 dark:border-white/10 py-1',
  signOutBtn: 'flex items-center gap-3 w-full px-4 py-2.5 text-sm text-sale hover:bg-sale/5 transition-colors',
} as const;
