export const wishlistTokens = {
  icon: {
    wrapper: 'relative hidden md:flex',
    btn: 'relative',
    badge: 'absolute -top-1 -right-1 w-[18px] h-[18px] bg-primary-btn rounded-full flex items-center justify-center text-xs font-medium text-bg-dark',
    dropdown: 'absolute right-0 top-full mt-2 w-80 bg-bg-white dark:bg-bg-surface rounded-card-lg shadow-newsletter border border-border-primary/10 dark:border-white/10 z-50 flex flex-col max-h-[80vh]',
    dropdownHeader: 'flex items-center px-4 py-3 border-b border-border-primary/10 dark:border-white/10 flex-shrink-0',
    dropdownTitle: 'text-sm font-semibold text-text-primary dark:text-text-on-dark',
    dropdownItems: 'overflow-y-auto flex-1 px-4',
    dropdownFooter: 'border-t border-border-primary/10 dark:border-white/10 px-4 py-3 flex-shrink-0',
    continueBtn: 'block w-full text-center text-xs font-medium text-text-primary dark:text-text-on-dark hover:text-primary-btn transition-colors',
  },
  emptyState: {
    wrapper: 'flex flex-col items-center justify-center gap-3 px-4 py-8',
    icon: 'w-10 h-10 text-text-placeholder',
    title: 'text-sm font-semibold text-text-primary dark:text-text-on-dark',
    sub: 'text-xs text-text-secondary dark:text-text-footer-link text-center',
    continueBtn: 'px-5 py-2 bg-primary-btn text-bg-dark rounded-btn-sm text-sm font-semibold hover:opacity-90 transition-opacity',
  },
  row: {
    wrapper: 'flex gap-3 py-3 border-b border-border-primary/10 dark:border-white/10 last:border-0',
    imageLink: 'relative w-16 h-16 flex-shrink-0 bg-bg-page dark:bg-bg-dark rounded-tag overflow-hidden',
    discountBadge: 'absolute top-0.5 left-0.5 px-1 py-0.5 bg-sale text-white text-[9px] font-semibold rounded leading-none',
    body: 'flex-1 min-w-0 flex flex-col justify-between',
    brand: 'text-xs text-text-secondary dark:text-text-footer-link',
    nameLink: 'text-sm font-medium text-text-primary dark:text-text-on-dark line-clamp-2 leading-tight hover:text-primary-btn transition-colors',
    price: 'text-sm font-semibold text-text-primary dark:text-text-on-dark',
    originalPrice: 'text-xs text-text-secondary dark:text-text-footer-link line-through',
    priceRow: 'flex items-center gap-2 mt-0.5',
    controls: 'flex items-center gap-2 mt-1.5',
    moveToCartBtn: 'flex items-center gap-1 px-2.5 py-1 bg-primary text-text-on-dark rounded-btn-sm text-xs font-semibold hover:bg-primary/90 transition-colors',
    removeBtn: 'w-7 h-7 flex items-center justify-center border border-border-primary/30 dark:border-white/10 rounded-btn-sm text-text-secondary hover:text-sale hover:border-sale transition-colors',
  },
} as const
