export const checkoutTokens = {
  page: {
    wrapper: 'min-h-[70vh] flex items-center justify-center px-site py-12',
    inner: 'max-w-content mx-auto px-site py-10',
    grid: 'grid grid-cols-1 lg:grid-cols-[1fr_420px] gap-8',
    formCard: 'bg-bg-white dark:bg-bg-surface rounded-card-lg p-6 md:p-8 space-y-6',
    sectionTitle: 'text-newsletter-sub font-semibold text-text-primary dark:text-text-on-dark',
  },
  orderSummary: {
    root: 'bg-bg-dark rounded-carousel p-6 text-text-on-dark space-y-5',
    title: 'text-newsletter-sub font-semibold',
    itemsList: 'space-y-3 max-h-48 overflow-y-auto',
    itemRow: 'flex gap-3',
    itemImageWrapper: 'relative w-12 h-12 flex-shrink-0 bg-bg-page/10 rounded-tag overflow-hidden',
    itemQtyBadge: 'absolute -top-1 -right-1 w-4 h-4 bg-text-primary text-bg-white text-xs rounded-full flex items-center justify-center font-semibold',
    itemName: 'text-xs font-medium line-clamp-2 leading-tight',
    itemPrice: 'text-xs font-semibold whitespace-nowrap',
    divider: 'border-text-on-dark/20',
    couponLabel: 'text-xs text-text-footer-link mb-2',
    totalsRow: 'flex justify-between text-nav-sm',
    totalsLabel: 'text-text-footer-link',
    discountRow: 'flex justify-between text-nav-sm text-success',
    totalRow: 'flex justify-between text-newsletter-sub font-semibold',
  },
  couponInput: {
    appliedWrapper: 'flex items-center gap-2 p-3 bg-success/10 rounded-btn-sm border border-success/30',
    appliedText: 'text-nav-sm font-medium text-success flex-1',
    removeBtn: 'text-xs text-text-secondary hover:text-text-primary',
    formRow: 'flex gap-2',
    input: 'flex-1 h-10 px-3 border border-border-primary/40 rounded-btn-sm text-nav-sm text-text-primary bg-bg-white focus:outline-none focus:border-primary',
    applyBtn: 'px-4 h-10 bg-primary text-text-on-dark rounded-btn-sm text-xs font-semibold disabled:opacity-50 hover:bg-primary/90 transition-colors whitespace-nowrap',
  },
  shippingMethod: {
    root: 'space-y-3',
    option: 'flex items-center gap-4 p-4 rounded-carousel border-2 cursor-pointer transition-colors',
    optionSelected: 'border-primary bg-primary/5',
    optionDefault: 'border-border-primary/20 hover:border-primary/50',
    label: 'text-nav-sm font-semibold text-text-primary',
    days: 'text-xs text-text-secondary',
    cost: 'text-nav-sm font-semibold text-text-primary',
  },
  paymentMethod: {
    root: 'space-y-3',
    option: 'flex items-start gap-4 p-4 rounded-carousel border-2 cursor-pointer transition-colors',
    optionSelected: 'border-primary bg-primary/5',
    optionDefault: 'border-border-primary/20 hover:border-primary/50',
    iconSelected: 'text-primary',
    iconDefault: 'text-text-secondary',
    label: 'text-nav-sm font-semibold text-text-primary',
    desc: 'text-xs text-text-secondary leading-relaxed',
  },
  fieldLabel: 'block text-nav-sm font-medium text-text-primary dark:text-text-on-dark mb-1.5',
  fieldInput: 'w-full h-10 px-3 border border-border-primary/40 dark:border-white/20 rounded-btn-sm text-nav-sm text-text-primary dark:text-text-on-dark bg-bg-white dark:bg-bg-surface focus:outline-none focus:border-primary',
  errorMsg: 'text-xs text-sale mt-1',
  submitBtn: 'w-full h-12 bg-primary text-text-on-dark rounded-btn-sm text-nav-sm font-semibold hover:bg-primary/90 transition-colors disabled:opacity-60',
} as const
