export const cartTokens = {
  page: {
    root: 'max-w-2xl mx-auto px-site py-12',
    skeleton: {
      list: 'space-y-4',
      item: 'h-24 bg-bg-white dark:bg-bg-surface rounded-carousel border border-border-primary/10 animate-pulse',
    },
    heading: 'text-section-heading font-semibold text-text-primary dark:text-text-on-dark mb-8',
    itemCount: 'ml-2 text-text-secondary dark:text-text-footer-link font-normal text-nav-sm',
    emptyWrapper: 'flex flex-col items-center justify-center py-20 text-center',
    emptyIcon: 'w-16 h-16 text-primary/20 mb-4',
    emptyTitle: 'text-section-heading font-semibold text-text-primary dark:text-text-on-dark mb-2',
    emptySub: 'text-nav-sm text-text-secondary dark:text-text-footer-link mb-6 max-w-sm',
    emptyBtn: 'px-6 py-3 bg-primary text-text-on-dark rounded-btn-sm text-nav-sm font-semibold hover:bg-primary/90 transition-colors',
    list: 'space-y-6',
    itemsCard: 'bg-bg-white dark:bg-bg-surface rounded-carousel border border-border-primary/10 divide-y divide-border-primary/10 dark:divide-white/10',
    itemPadding: 'px-5 py-4',
    summaryCard: 'bg-bg-white dark:bg-bg-surface rounded-carousel border border-border-primary/10 p-5 space-y-3',
    subtotalRow: 'flex justify-between items-center',
    subtotalLabel: 'text-nav-sm font-medium text-text-primary dark:text-text-on-dark',
    subtotalValue: 'text-newsletter-sub font-semibold text-text-primary dark:text-text-on-dark',
    shippingNote: 'text-xs text-text-secondary dark:text-text-footer-link',
    checkoutBtn: 'block w-full py-3 bg-primary-btn text-bg-dark rounded-btn-sm text-nav-sm font-semibold text-center hover:bg-primary transition-colors',
    continueBtn: 'block w-full text-center text-nav-sm font-medium text-text-primary dark:text-text-on-dark hover:text-primary-btn dark:hover:text-primary-btn transition-colors',
  },
} as const;
