export const cartTokens = {
  drawer: {
    overlay: 'fixed inset-0 z-[52] bg-black/50',
    panel: 'fixed top-0 right-0 z-[55] h-full w-full max-w-md bg-bg-white dark:bg-bg-surface shadow-xl flex flex-col',
    header: 'flex items-center justify-between px-6 py-4 border-b border-border-primary/20 dark:border-white/10',
    title: 'text-newsletter-sub font-semibold text-text-primary dark:text-text-on-dark',
    closeBtn: 'p-1 text-text-primary dark:text-text-on-dark hover:text-primary-btn transition-colors',
    itemsList: 'flex-1 overflow-y-auto px-6 py-4 space-y-4',
    footer: 'border-t border-border-primary/20 dark:border-white/10 px-6 py-4 space-y-3',
    subtotalRow: 'flex justify-between items-center',
    subtotalLabel: 'text-nav-sm font-medium text-text-primary dark:text-text-on-dark',
    subtotalValue: 'text-newsletter-sub font-semibold text-text-primary dark:text-text-on-dark',
    shippingNote: 'text-xs text-text-secondary dark:text-text-footer-link',
    checkoutBtn: 'block w-full py-3 bg-primary-btn text-text-on-dark rounded-btn-sm text-nav-sm font-semibold text-center hover:bg-primary transition-colors',
    continueBtn: 'block w-full text-center text-nav-sm font-medium text-text-primary dark:text-text-on-dark hover:text-primary-btn dark:hover:text-primary-btn transition-colors',
  },
  emptyState: {
    wrapper: 'flex-1 flex flex-col items-center justify-center gap-4 px-6 py-12',
    icon: 'w-16 h-16 text-text-placeholder dark:text-text-footer-link',
    title: 'text-nav-sm font-semibold text-text-primary dark:text-text-on-dark',
    sub: 'text-nav-sm text-text-secondary dark:text-text-footer-link text-center',
    startBtn: 'px-6 py-3 bg-primary-btn text-text-on-dark rounded-btn-sm text-nav-sm font-semibold hover:bg-primary transition-colors',
  },
  icon: {
    mobileLink: 'relative md:hidden',
    desktopWrapper: 'relative hidden md:block',
    wrapper: 'relative',
    btn: 'relative',
    cartIcon: 'w-6 h-6 text-text-primary dark:text-text-on-dark',
    badge: 'absolute -top-1 -right-1 w-[18px] h-[18px] bg-primary-btn rounded-full flex items-center justify-center text-xs font-medium text-bg-dark',
    dropdown: 'absolute right-0 top-full mt-2 w-80 bg-bg-white dark:bg-bg-surface rounded-card-lg shadow-newsletter border border-border-primary/10 dark:border-white/10 z-50 flex flex-col max-h-[80vh]',
    dropdownHeader: 'flex items-center px-4 py-3 border-b border-border-primary/10 dark:border-white/10 flex-shrink-0',
    dropdownTitle: 'text-sm font-semibold text-text-primary dark:text-text-on-dark',
    dropdownItemCount: 'ml-1 text-text-secondary dark:text-text-footer-link font-normal',
    dropdownEmptyWrapper: 'flex flex-col items-center justify-center gap-3 px-4 py-8',
    dropdownEmptyIcon: 'w-12 h-12 text-text-placeholder',
    dropdownEmptyTitle: 'text-sm font-semibold text-text-primary dark:text-text-on-dark',
    dropdownEmptySub: 'text-xs text-text-secondary dark:text-text-footer-link text-center',
    dropdownEmptyBtn: 'px-5 py-2 bg-primary-btn text-bg-dark rounded-btn-sm text-sm font-semibold hover:opacity-90 transition-opacity',
    dropdownItems: 'overflow-y-auto flex-1 px-4 py-3 space-y-3',
    dropdownFooter: 'border-t border-border-primary/10 dark:border-white/10 px-4 py-3 space-y-2 flex-shrink-0',
    dropdownSubtotalRow: 'flex justify-between items-center',
    dropdownSubtotalLabel: 'text-sm font-medium text-text-primary dark:text-text-on-dark',
    dropdownSubtotalValue: 'text-sm font-semibold text-text-primary dark:text-text-on-dark',
    dropdownCheckoutBtn: 'block w-full py-2.5 bg-primary-btn text-bg-dark rounded-btn-sm text-sm font-semibold text-center hover:opacity-90 transition-opacity',
    dropdownContinueBtn: 'block w-full text-center text-xs font-medium text-text-primary dark:text-text-on-dark hover:text-primary-btn transition-colors',
  },
  itemAttributes: {
    wrapper: 'flex items-center gap-1.5 flex-wrap mt-0.5',
    colorCircle: 'w-4 h-4 rounded-full border border-border-primary/30 dark:border-white/20 shrink-0',
    text: 'text-xs text-text-secondary dark:text-text-footer-link',
  },
  itemNote: 'text-xs text-text-secondary dark:text-text-footer-link italic mt-0.5 line-clamp-2',
  item: {
    drawer: {
      wrapper: 'flex gap-3',
      imageWrapper: 'relative w-16 h-16 flex-shrink-0 bg-bg-page dark:bg-bg-dark rounded-tag overflow-hidden',
      body: 'flex-1 min-w-0',
      name: 'text-nav-sm font-medium text-text-primary dark:text-text-on-dark line-clamp-2 leading-tight',
      unitPrice: 'text-xs text-text-secondary dark:text-text-footer-link mt-0.5',
      controls: 'flex items-center justify-between mt-2',
      stepper: 'flex items-center border border-border-primary/30 dark:border-white/10 rounded-full overflow-hidden',
      stepperBtn: 'w-7 h-7 flex items-center justify-center text-text-primary dark:text-text-on-dark disabled:opacity-40 hover:bg-bg-page dark:hover:bg-bg-dark transition-colors',
      stepperQty: 'w-8 text-center text-xs font-semibold text-text-primary dark:text-text-on-dark',
      removeBtn: 'text-text-placeholder dark:text-text-footer-link hover:text-sale transition-colors',
      totalPrice: 'text-nav-sm font-semibold text-text-primary dark:text-text-on-dark flex-shrink-0',
    },
    dropdown: {
      imageWrapper: 'relative w-14 h-14 flex-shrink-0 bg-bg-page dark:bg-bg-dark rounded-tag overflow-hidden',
      name: 'text-xs font-medium text-text-primary dark:text-text-on-dark line-clamp-2 leading-tight',
      stepperBtn: 'w-6 h-6 flex items-center justify-center text-text-primary dark:text-text-on-dark disabled:opacity-40 hover:bg-bg-page dark:hover:bg-bg-dark transition-colors',
      stepperQty: 'w-6 text-center text-xs font-semibold text-text-primary dark:text-text-on-dark',
      totalPrice: 'text-xs font-semibold text-text-primary dark:text-text-on-dark flex-shrink-0',
      controls: 'flex items-center justify-between mt-1.5',
    },
  },
  page: {
    root: 'max-w-2xl mx-auto px-site py-12',
    skeleton: {
      list: 'space-y-4',
      item: 'h-24 bg-bg-white dark:bg-bg-surface rounded-carousel border border-border-primary/10 animate-pulse',
    },
    heading: 'text-section-heading font-semibold text-text-primary dark:text-text-on-dark mb-8',
    itemCount: 'ml-2 text-text-secondary dark:text-text-footer-link font-normal text-nav-sm',
    emptyWrapper: 'flex flex-col items-center justify-center py-20 text-center',
    emptyIcon: 'w-16 h-16 text-primary/20 mb-4',
    emptyTitle: 'text-section-heading font-semibold text-text-primary dark:text-text-on-dark mb-2',
    emptySub: 'text-nav-sm text-text-secondary dark:text-text-footer-link mb-6 max-w-sm',
    emptyBtn: 'px-6 py-3 bg-primary text-text-on-dark rounded-btn-sm text-nav-sm font-semibold hover:bg-primary/90 transition-colors',
    list: 'space-y-6',
    itemsCard: 'bg-bg-white dark:bg-bg-surface rounded-carousel border border-border-primary/10 divide-y divide-border-primary/10 dark:divide-white/10',
    itemPadding: 'px-5 py-4',
    summaryCard: 'bg-bg-white dark:bg-bg-surface rounded-carousel border border-border-primary/10 p-5 space-y-3',
    subtotalRow: 'flex justify-between items-center',
    subtotalLabel: 'text-nav-sm font-medium text-text-primary dark:text-text-on-dark',
    subtotalValue: 'text-newsletter-sub font-semibold text-text-primary dark:text-text-on-dark',
    shippingNote: 'text-xs text-text-secondary dark:text-text-footer-link',
    checkoutBtn: 'block w-full py-3 bg-primary-btn text-bg-dark rounded-btn-sm text-nav-sm font-semibold text-center hover:bg-primary transition-colors',
    continueBtn: 'block w-full text-center text-nav-sm font-medium text-text-primary dark:text-text-on-dark hover:text-primary-btn dark:hover:text-primary-btn transition-colors',
  },
} as const;
