export const cartIconTokens = {
  mobileLink: 'relative md:hidden',
  desktopWrapper: 'relative hidden md:block',
  btn: 'relative',
  cartIcon: 'w-6 h-6 text-text-primary dark:text-text-on-dark',
  badge: 'absolute -top-1 -right-1 w-[18px] h-[18px] bg-primary-btn rounded-full flex items-center justify-center text-xs font-medium text-bg-dark',
  dropdown: 'absolute right-0 top-full mt-2 w-80 bg-bg-white dark:bg-bg-surface rounded-card-lg shadow-newsletter border border-border-primary/10 dark:border-white/10 z-50 flex flex-col max-h-[80vh]',
  dropdownHeader: 'flex items-center px-4 py-3 border-b border-border-primary/10 dark:border-white/10 flex-shrink-0',
  dropdownTitle: 'text-sm font-semibold text-text-primary dark:text-text-on-dark',
  dropdownItemCount: 'ml-1 text-text-secondary dark:text-text-footer-link font-normal',
  dropdownEmptyWrapper: 'flex flex-col items-center justify-center gap-3 px-4 py-8',
  dropdownEmptyIcon: 'w-12 h-12 text-text-placeholder',
  dropdownEmptyTitle: 'text-sm font-semibold text-text-primary dark:text-text-on-dark',
  dropdownEmptySub: 'text-xs text-text-secondary dark:text-text-footer-link text-center',
  dropdownEmptyBtn: 'px-5 py-2 bg-primary-btn text-bg-dark rounded-btn-sm text-sm font-semibold hover:opacity-90 transition-opacity',
  dropdownItems: 'overflow-y-auto flex-1 px-4 py-3 space-y-3',
  dropdownFooter: 'border-t border-border-primary/10 dark:border-white/10 px-4 py-3 space-y-2 flex-shrink-0',
  dropdownSubtotalRow: 'flex justify-between items-center',
  dropdownSubtotalLabel: 'text-sm font-medium text-text-primary dark:text-text-on-dark',
  dropdownSubtotalValue: 'text-sm font-semibold text-text-primary dark:text-text-on-dark',
  dropdownShippingNote: 'text-xs text-text-secondary dark:text-text-footer-link',
  dropdownCheckoutBtn: 'block w-full py-2.5 bg-primary-btn text-bg-dark rounded-btn-sm text-sm font-semibold text-center hover:opacity-90 transition-opacity',
  dropdownContinueBtn: 'block w-full text-center text-xs font-medium text-text-primary dark:text-text-on-dark hover:text-primary-btn transition-colors',
} as const;
