export const productTokens = {
  root: '',
  card: {
    root: 'group relative flex flex-col bg-bg-white dark:bg-bg-surface rounded-carousel border border-border-primary/10 dark:border-white/10 overflow-hidden hover:shadow-md transition-shadow',
    linkWrapper: 'block flex-1',
    imageWrapper: 'relative aspect-square bg-bg-page dark:bg-bg-dark overflow-hidden',
    image: 'object-contain p-4 group-hover:scale-105 transition-transform duration-300',
    discountBadge: 'absolute top-2 left-2 px-2 py-0.5 bg-sale text-text-on-dark text-xs font-semibold rounded-tag',
    outOfStockOverlay: 'absolute inset-0 bg-bg-white/70 dark:bg-bg-surface/70 flex items-center justify-center',
    outOfStockLabel: 'text-sm font-semibold text-text-secondary dark:text-text-footer-link',
    body: 'p-4',
    brand: 'text-xs text-text-secondary dark:text-text-footer-link font-medium mb-1',
    name: 'text-base font-semibold text-text-primary dark:text-text-on-dark leading-tight line-clamp-2 mb-2',
    actions: 'px-4 pb-4 flex flex-col gap-2',
    wishlistWrapper: 'absolute top-2 right-2',
  },
  cardActions: {
    wishlistBtn: 'flex items-center justify-center w-8 h-8 rounded-full bg-bg-white/90 dark:bg-bg-surface/90 hover:bg-bg-white dark:hover:bg-bg-surface shadow-sm transition-colors',
    wishlistIcon: {
      active: 'w-4 h-4 fill-sale text-sale',
      inactive: 'w-4 h-4 text-text-primary dark:text-text-on-dark',
    },
    quickAddBtn: 'flex items-center justify-center gap-1.5 w-full py-2 bg-primary-btn text-text-on-dark rounded-btn-sm text-xs font-semibold disabled:opacity-50 disabled:cursor-not-allowed hover:bg-primary transition-colors',
  },
  grid: {
    root: 'grid grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-4 md:gap-6',
    skeletonCard: 'bg-bg-white dark:bg-bg-surface rounded-carousel border border-border-primary/10 overflow-hidden animate-pulse',
    skeletonImage: 'aspect-square bg-bg-page dark:bg-bg-dark',
    skeletonBody: 'p-4 space-y-2',
    skeletonLine: 'bg-bg-page dark:bg-bg-dark rounded',
    skeletonBtn: 'h-9 bg-bg-page dark:bg-bg-dark rounded-btn-sm w-full',
  },
  gallery: {
    root: 'flex flex-col gap-4',
    mainImage: 'relative aspect-square bg-bg-page dark:bg-bg-dark rounded-carousel overflow-hidden group',
    mainImageImg: 'object-contain p-6 transition-transform duration-300 group-hover:scale-110',
    thumbs: 'flex gap-2 overflow-x-auto pb-1',
    thumb: 'relative flex-shrink-0 w-16 h-16 rounded-tag border-2 overflow-hidden bg-bg-page dark:bg-bg-dark transition-colors',
    thumbActive: 'border-primary',
    thumbInactive: 'border-border-primary/20 dark:border-white/15 hover:border-primary/50',
  },
  detail: {
    brand: 'text-xs text-text-secondary dark:text-text-footer-link font-medium mb-1',
    addToCartWrapper: 'space-y-4',
    addToCartSkeleton: 'space-y-4 animate-pulse',
    addToCartBtn: 'flex-1 flex items-center justify-center gap-2 py-3 bg-primary-btn text-text-on-dark rounded-btn-sm text-nav-sm font-semibold disabled:opacity-50 disabled:cursor-not-allowed hover:bg-primary transition-colors',
    wishlistBtn: 'flex items-center justify-center w-12 h-12 border border-border-primary/40 dark:border-white/20 rounded-btn-sm hover:border-primary transition-colors',
    wishlistIcon: {
      active: 'w-5 h-5 fill-sale text-sale',
      inactive: 'w-5 h-5 text-text-primary dark:text-text-on-dark',
    },
    outOfStockMsg: 'text-nav-sm text-text-secondary',
    actionsRow: 'flex gap-3',
    noteLabel: 'block text-sm font-medium text-text-primary dark:text-text-on-dark mb-1',
    noteTextarea: 'w-full px-3 py-2.5 border border-border-primary/30 dark:border-white/15 rounded-lg text-sm text-text-primary dark:text-text-on-dark bg-bg-white dark:bg-bg-surface placeholder-text-placeholder dark:placeholder-text-footer-link focus:outline-none focus:ring-2 focus:ring-primary/30 resize-none transition-colors',
  },
  specs: {
    grid: 'grid grid-cols-2 gap-3',
    item: 'flex items-center gap-2 p-3 bg-bg-page dark:bg-bg-surface rounded-tag',
    icon: 'w-4 h-4 text-primary-btn flex-shrink-0',
    label: 'text-xs text-text-secondary dark:text-text-footer-link',
    value: 'text-nav-sm font-medium text-text-primary dark:text-text-on-dark',
  },
  review: {
    form: 'mb-8 p-5 border border-border-primary/20 rounded-xl space-y-4 bg-bg-white dark:bg-bg-surface',
    formTitle: 'text-base font-semibold text-text-primary',
    input: 'w-full px-3 py-2 border border-border-primary/30 rounded-lg text-sm text-text-primary bg-bg-white dark:bg-bg-surface focus:outline-none focus:ring-2 focus:ring-primary/30 transition-colors',
    label: 'block text-sm text-text-secondary mb-1',
    errorMsg: 'text-sm text-sale font-medium',
    successMsg: 'mb-6 p-4 bg-success/10 rounded-lg text-sm text-success font-medium',
    submitBtn: 'flex items-center gap-2 px-5 py-2.5 bg-primary-btn text-white text-sm font-medium rounded-lg hover:bg-primary-btn/90 disabled:opacity-50 transition-colors',
    list: 'space-y-6',
    listItem: 'border-b border-border-primary/10 pb-6 last:border-0',
    listMeta: 'flex items-start gap-3 mb-2',
    avatarWrapper: 'relative w-9 h-9 rounded-full overflow-hidden bg-bg-page flex-shrink-0',
    reviewerName: 'text-nav-sm font-semibold text-text-primary',
    reviewDate: 'ml-auto text-xs text-text-secondary',
    reviewTitle: 'text-nav-sm font-semibold text-text-primary mb-1',
    reviewBody: 'text-nav-sm text-text-body leading-relaxed',
    emptyMsg: 'text-nav-sm text-text-secondary py-8 text-center',
  },
  quantityOffer: {
    popup: {
      overlay: 'fixed inset-0 z-50 flex items-end sm:items-center justify-center p-4 bg-black/40 backdrop-blur-sm',
      panel: 'relative w-full max-w-sm bg-bg-white dark:bg-bg-surface rounded-2xl shadow-2xl p-6 border border-border-primary/20',
      closeBtn: 'absolute top-4 right-4 text-text-secondary hover:text-text-primary transition-colors',
      iconWrapper: 'w-10 h-10 rounded-full bg-primary/10 dark:bg-white/10 flex items-center justify-center shrink-0',
      icon: 'w-5 h-5 text-primary dark:text-white/70',
      eyebrow: 'text-xs font-semibold text-primary dark:text-white/60 uppercase tracking-wide',
      productName: 'text-sm font-semibold text-text-primary dark:text-text-on-dark line-clamp-1',
      offerCard: 'rounded-xl bg-primary/5 dark:bg-white/5 border border-primary/20 dark:border-white/10 p-4',
      offerTitle: 'text-base font-bold text-text-primary dark:text-text-on-dark',
      offerSavings: 'text-sm text-text-secondary dark:text-text-on-dark/60 mt-1',
      ctaBtn: 'mt-4 w-full py-2.5 rounded-xl bg-primary text-white font-medium text-sm hover:bg-primary/90 transition-colors',
    },
    banner: {
      root: 'rounded-xl border border-primary/25 bg-primary/5 dark:bg-white/5 dark:border-white/10 p-5',
      header: 'flex items-center gap-2 mb-3',
      icon: 'w-4 h-4 text-primary dark:text-white/70 shrink-0',
      title: 'text-sm font-semibold text-text-primary dark:text-text-on-dark',
      list: 'space-y-2.5',
      row: 'flex items-center justify-between gap-4 text-sm',
      label: 'text-text-body dark:text-text-on-dark/80',
      price: 'font-semibold text-primary dark:text-white',
      savings: 'text-xs font-medium text-sale',
    },
  },
  variantSelector: {
    root: 'space-y-4',
    groupLabel: 'text-nav-sm font-semibold text-text-primary dark:text-text-on-dark mb-2 capitalize flex items-center gap-2',
    colorHint: 'text-xs font-mono font-normal text-text-secondary',
    optionRow: 'flex flex-wrap gap-2',
    colorBtn: 'w-8 h-8 rounded-full border-2 transition-all focus:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-1',
    colorBtnSelected: 'border-primary ring-2 ring-primary ring-offset-2 dark:ring-offset-bg-surface',
    colorBtnAvailable: 'border-transparent hover:border-primary/60',
    colorBtnUnavailable: 'border-transparent opacity-30 cursor-not-allowed',
    sizeBtn: 'px-4 py-2 rounded-btn-sm border text-nav-sm font-medium transition-colors',
    sizeBtnSelected: 'border-primary bg-primary text-text-on-dark',
    sizeBtnInStock: 'border-border-primary/40 dark:border-white/20 text-text-primary dark:text-text-on-dark hover:border-primary',
    sizeBtnOutOfStock: 'border-border-primary/30 dark:border-white/15 text-text-placeholder dark:text-text-footer-link/50 line-through cursor-not-allowed',
    sizeBtnUnavailable: 'border-border-primary/20 dark:border-white/10 text-text-placeholder dark:text-text-footer-link/50 opacity-50 cursor-not-allowed',
  },
  quantitySelector: {
    root: 'flex items-center border border-border-primary/40 dark:border-white/20 rounded-stepper overflow-hidden w-fit',
    btn: 'flex items-center justify-center w-10 h-10 text-text-primary dark:text-text-on-dark hover:bg-bg-page dark:hover:bg-bg-surface disabled:opacity-40 disabled:cursor-not-allowed transition-colors',
    input: 'w-12 text-center text-nav-sm font-semibold text-text-primary dark:text-text-on-dark bg-transparent border-x border-border-primary/40 dark:border-white/20 focus:outline-none',
  },
  offerBanner: {
    root: 'space-y-2',
    item: 'flex items-start gap-2.5 px-4 py-3 rounded-lg bg-primary/10 dark:bg-white/10 border border-primary/20 dark:border-white/20 text-sm text-text-primary dark:text-text-on-dark',
    icon: 'w-4 h-4 shrink-0 mt-0.5 text-primary dark:text-white/70',
    rewardLink: 'font-semibold underline underline-offset-2 hover:text-primary transition-colors',
  },
  relatedProducts: {
    heading: 'text-newsletter-sub font-semibold text-text-primary mb-6',
    grid: 'grid grid-cols-2 md:grid-cols-4 gap-4 md:gap-6',
  },
} as const
