export const homeTokens = {
  section: {
    base: 'py-12 bg-bg-page dark:bg-bg-dark',
    inner: 'max-w-content mx-auto px-site',
    header: 'flex items-center justify-between mb-8',
    heading: 'text-2xl md:text-3xl font-semibold text-text-primary dark:text-text-on-dark',
    viewAllLink: 'inline-flex items-center gap-1.5 text-sm font-semibold text-primary-btn hover:underline',
    grid4: 'grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4',
    grid5: 'grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4',
  },
  hero: {
    root: 'relative bg-primary dark:bg-white overflow-hidden min-h-[280px] md:min-h-hero',
    glow: 'absolute right-0 top-1/2 -translate-y-1/2 w-[300px] md:w-[400px] h-[300px] md:h-[400px] rounded-full bg-primary-btn/20 blur-2xl will-change-transform pointer-events-none',
    inner: 'relative max-w-content mx-auto px-site py-12 md:py-0 md:h-hero flex items-center',
    content: 'max-w-xl',
    eyebrow: 'text-xs md:text-nav-sm font-medium text-text-footer-link dark:text-text-secondary mb-2 md:mb-3 uppercase tracking-widest',
    heading: 'font-secondary text-5xl sm:text-6xl md:text-7xl font-black uppercase leading-none tracking-tight text-text-on-dark dark:text-text-primary mb-3 md:mb-4',
    headingAccent: 'text-primary-btn',
    sub: 'text-base md:text-lg text-text-footer-link dark:text-text-secondary mb-6 md:mb-8 leading-relaxed',
    ctaRow: 'flex flex-wrap gap-3',
    primaryCta: 'px-6 md:px-8 py-3 md:py-3.5 bg-primary-btn text-bg-dark rounded-btn-sm text-sm font-semibold hover:bg-primary-btn/90 transition-colors',
    secondaryCta: 'px-6 md:px-8 py-3 md:py-3.5 border-2 border-text-on-dark dark:border-text-primary text-text-on-dark dark:text-text-primary rounded-btn-sm text-sm font-semibold hover:bg-text-on-dark/10 dark:hover:bg-text-primary/10 transition-colors',
  },
  categoryCards: {
    section: 'py-12 md:py-16 bg-bg-page dark:bg-bg-dark',
    inner: 'max-w-content mx-auto px-site',
    header: 'flex flex-col md:flex-row md:items-end justify-between mb-8 gap-3',
    eyebrow: 'text-xs font-semibold uppercase tracking-widest text-primary-btn mb-1',
    heading: 'font-secondary text-3xl md:text-5xl font-black uppercase tracking-tight text-text-primary dark:text-text-on-dark',
    viewAllLink: 'inline-flex items-center gap-1.5 text-sm font-semibold text-text-secondary dark:text-text-footer-link hover:text-primary-btn dark:hover:text-primary-btn transition-colors self-start md:self-auto',
    largeGrid: 'grid gap-4 mb-4',
    smallGrid: 'grid grid-cols-2 md:grid-cols-4 gap-4',
    card: 'group relative overflow-hidden rounded-card-lg flex flex-col justify-between p-5 md:p-6 border border-white/5 hover:border-white/15 transition-all duration-300 hover:scale-[1.015] cursor-pointer',
    cardOverlay: 'absolute inset-0 bg-black/50 group-hover:bg-black/40 transition-colors',
    cardFallback: 'absolute inset-0 bg-gradient-to-br from-[#111111] to-[#1e1e1e]',
    cardDot: 'relative z-10 w-2 h-2 rounded-full bg-primary-btn flex-shrink-0',
    cardName: 'font-secondary text-xl md:text-2xl font-black uppercase tracking-tight text-white leading-none',
    cardShopLabel: 'flex items-center gap-1 text-xs text-white/50 mt-1.5 group-hover:text-white/75 transition-colors',
  },
  trust: {
    section: 'py-10 bg-bg-white dark:bg-bg-surface',
    inner: 'max-w-content mx-auto px-site',
    grid: 'grid grid-cols-2 md:grid-cols-4 gap-6',
    item: 'flex flex-col gap-2 p-4 rounded-carousel border border-border-primary/10 dark:border-white/10',
    title: 'text-sm font-semibold text-text-primary dark:text-text-on-dark',
    desc: 'text-xs text-text-secondary dark:text-text-footer-link leading-relaxed',
  },
  newsletter: {
    section: 'py-10 md:py-14 bg-bg-page dark:bg-bg-dark',
    inner: 'max-w-content mx-auto px-site',
    card: 'bg-bg-white dark:bg-bg-surface rounded-card-lg shadow-newsletter px-4 sm:px-8 py-8 md:py-10 flex flex-col md:flex-row items-center gap-6',
    textBlock: 'flex-1 text-center md:text-start',
    heading: 'font-secondary text-2xl md:text-3xl font-black uppercase tracking-tight text-text-near-black dark:text-text-on-dark mb-2',
    sub: 'text-sm text-text-muted dark:text-text-footer-link leading-relaxed',
    successMsg: 'text-sm font-semibold text-success flex-shrink-0',
    form: 'flex flex-col sm:flex-row w-full md:w-auto gap-3',
    input: 'w-full sm:w-64 md:w-72 h-12 md:h-14 px-4 md:px-5 border border-border-primary/40 dark:border-white/20 rounded-input text-base text-text-primary dark:text-text-on-dark bg-bg-page dark:bg-bg-dark placeholder:text-text-placeholder dark:placeholder:text-text-footer-link focus:outline-none focus:border-primary',
    submitBtn: 'w-full sm:w-auto px-6 h-12 md:h-14 bg-primary text-text-on-dark rounded-input text-base font-semibold whitespace-nowrap disabled:opacity-60 hover:bg-primary/90 transition-colors',
  },
} as const
