export const shopTokens = {
  layout: {
    page: 'min-h-screen bg-bg-page dark:bg-bg-dark',
    inner: 'max-w-content mx-auto px-site py-8',
    grid: 'flex gap-8',
    sidebar: 'hidden lg:block w-sidebar flex-shrink-0',
    main: 'flex-1 min-w-0',
    topBar: 'flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-6',
  },
  filterSidebar: {
    root: 'space-y-6 transition-opacity',
    sectionTitle: 'text-nav-sm font-semibold text-text-primary dark:text-text-on-dark mb-3',
    radioLabel: 'flex items-center gap-2 cursor-pointer',
    radioText: 'text-nav-sm text-text-primary dark:text-text-on-dark',
    divider: 'border-border-primary/20 dark:border-white/10',
    priceRow: 'flex gap-2 items-center',
    priceInput: 'w-full h-9 px-3 border border-border-primary/40 dark:border-white/20 rounded-btn-sm text-nav-sm text-text-primary dark:text-text-on-dark bg-bg-white dark:bg-bg-surface focus:outline-none focus:border-primary',
  },
  filterDrawer: {
    triggerBtn: 'w-full flex items-center justify-center gap-2 px-4 py-2.5 border border-border-primary dark:border-white/20 rounded-btn-sm text-base font-medium text-text-primary dark:text-text-on-dark bg-bg-white dark:bg-bg-surface',
    overlay: 'fixed inset-0 z-[52] bg-black/50',
    panel: 'fixed top-0 right-0 z-[55] h-full w-80 bg-bg-white dark:bg-bg-surface shadow-xl flex flex-col',
    header: 'flex items-center justify-between px-6 py-4 border-b border-border-primary/20 dark:border-white/10 flex-shrink-0',
    headerTitle: 'text-base font-semibold text-text-primary dark:text-text-on-dark',
    closeBtn: 'p-1 text-text-primary dark:text-text-on-dark hover:text-primary',
    body: 'flex-1 overflow-y-auto overscroll-contain px-6 py-4',
    footer: 'px-6 py-4 border-t border-border-primary/20 dark:border-white/10 flex-shrink-0',
    applyBtn: 'w-full py-3 bg-primary text-text-on-dark rounded-btn-sm text-base font-semibold',
  },
  filterChips: {
    wrapper: 'flex flex-wrap gap-2 items-center',
    chip: 'flex items-center gap-1.5 px-3 py-1.5 bg-primary text-text-on-dark rounded-tag text-xs font-medium hover:bg-primary/90 transition-colors',
    clearAll: 'text-xs font-medium text-primary hover:underline',
  },
  sortDropdown: {
    wrapper: 'flex items-center gap-2 w-full',
    label: 'text-base font-medium text-text-primary dark:text-text-on-dark whitespace-nowrap',
    select: 'flex-1 h-10 px-3 pr-8 border border-border-primary dark:border-white/20 rounded-btn-sm text-base text-text-primary dark:text-text-on-dark bg-bg-white dark:bg-bg-surface focus:outline-none focus:ring-2 focus:ring-primary appearance-none disabled:opacity-50',
  },
  resultsCount: {
    text: 'text-nav-sm text-text-secondary dark:text-text-footer-link',
  },
  resultsPending: {
    overlay: 'absolute inset-0 bg-bg-page/60 rounded z-10 pointer-events-none',
  },
  noResults: {
    wrapper: 'flex flex-col items-center justify-center py-20 text-center',
    iconWrapper: 'w-24 h-24 mb-6 flex items-center justify-center rounded-full bg-bg-page dark:bg-bg-surface',
    icon: 'w-12 h-12 text-text-placeholder',
    title: 'text-newsletter-sub font-semibold text-text-primary dark:text-text-on-dark mb-2',
    sub: 'text-nav-sm text-text-secondary dark:text-text-footer-link max-w-sm mb-6',
    btnRow: 'flex gap-3',
    clearBtn: 'px-6 py-2.5 bg-primary dark:bg-bg-white text-text-on-dark dark:text-text-primary rounded-btn-sm text-nav-sm font-semibold hover:bg-primary/90 dark:hover:bg-bg-page transition-colors',
    viewAllLink: 'px-6 py-2.5 border border-border-primary dark:border-white/20 text-text-primary dark:text-text-on-dark rounded-btn-sm text-nav-sm font-semibold hover:bg-bg-page dark:hover:bg-bg-surface transition-colors',
  },
  pagination: {
    nav: 'flex items-center justify-center gap-1 mt-8',
    btn: 'flex items-center justify-center w-10 h-10 rounded-btn-sm border border-border-primary/30 dark:border-white/20 text-text-primary dark:text-text-on-dark disabled:opacity-40 disabled:cursor-not-allowed hover:border-primary hover:text-primary transition-colors',
    pageBtn: 'flex items-center justify-center w-10 h-10 rounded-btn-sm border text-nav-sm transition-colors',
    pageBtnActive: 'border-primary bg-primary text-text-on-dark font-semibold',
    pageBtnInactive: 'border-border-primary/30 dark:border-white/20 text-text-primary dark:text-text-on-dark hover:border-primary hover:text-primary',
    ellipsis: 'w-10 text-center text-text-secondary dark:text-text-footer-link',
  },
} as const
