export const GOVERNORATES = [
  'Cairo',
  'Alexandria',
  'Giza',
  'Qalyubia',
  'Port Said',
  'Suez',
  'Dakahlia',
  'Sharqia',
  'Gharbia',
  'Monufia',
  'Beheira',
  'Kafr El Sheikh',
  'Damietta',
  'Ismailia',
  'Faiyum',
  'Beni Suef',
  'Minya',
  'Asyut',
  'Sohag',
  'Qena',
  'Luxor',
  'Aswan',
  'Red Sea',
  'New Valley',
  'Matrouh',
  'North Sinai',
  'South Sinai',
] as const;

export type Governorate = (typeof GOVERNORATES)[number];

export const GOVERNORATE_NAMES_AR: Record<Governorate, string> = {
  Cairo: 'القاهرة',
  Alexandria: 'الإسكندرية',
  Giza: 'الجيزة',
  Qalyubia: 'القليوبية',
  'Port Said': 'بورسعيد',
  Suez: 'السويس',
  Dakahlia: 'الدقهلية',
  Sharqia: 'الشرقية',
  Gharbia: 'الغربية',
  Monufia: 'المنوفية',
  Beheira: 'البحيرة',
  'Kafr El Sheikh': 'كفر الشيخ',
  Damietta: 'دمياط',
  Ismailia: 'الإسماعيلية',
  Faiyum: 'الفيوم',
  'Beni Suef': 'بني سويف',
  Minya: 'المنيا',
  Asyut: 'أسيوط',
  Sohag: 'سوهاج',
  Qena: 'قنا',
  Luxor: 'الأقصر',
  Aswan: 'أسوان',
  'Red Sea': 'البحر الأحمر',
  'New Valley': 'الوادي الجديد',
  Matrouh: 'مطروح',
  'North Sinai': 'شمال سيناء',
  'South Sinai': 'جنوب سيناء',
};
